### ISSUE TITLE
Project page seems flat??

### ISSUE THREAD

**Issue by Jakestudiofriday** [markendley/lme#13]
Project page seems flat??

I'd like to add some animation to the images or perhaps lightbox the image to add some interactive to the pages?

any other ideas? or thoughts

**Comment by markendley** [comment]
Here are my ideas...

Home page - on load the image zooms-in slowly

Project gallery page - each each fades in one after the other

Project page - each image slides/fades in from the left hand side as you scroll to the right.
AND/OR I can make the images grayscle, and then they become full color once you scroll to it.


If I may: the lightbox will be pointless because the images are already big.

**Comment by markendley** [comment]
Project gallery page - each each fades in one after the other

Project page - each image slides/fades in from the left hand side as you scroll to the right.

**Comment by markendley** [comment]
ready, how's that?
